### ISSUE TITLE
Profile URL doesn't work with new identity package?

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/ms-identity-python-webapp#107]
I'm just doing some testing with the B2C flow, and noticing that the edit profile URL results in an error:

https://pythonb2c.b2clogin.com/pythonb2c.onmicrosoft.com/B2C_1_reset_password?client_id=64dceede-19bb-4f48-bafe-0b99daca5005

"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

That's from this link formation:

```
    {% if config.get("B2C_PROFILE_AUTHORITY") %}
      <li><a href='{{config.get("B2C_PROFILE_AUTHORITY")}}?client_id={{config.get("CLIENT_ID")}}'>Edit Profile</a></li>
    {% endif %}
```

Looking back at how the sample previously did it, using msal, it seems we need to build_msal_appp using that authority URL. 

https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-python-web-app?tabs=macos#step-5-add-the-web-app-code

I think I could probably hack it using the current identity package by creating a new Auth object, but that doesn't seem intended. Should the identity package be extended to have additional constructor arguments, perhaps? And a profile() method?

**Comment by jimma72** [comment]
@pamelafox , thank you for highlighting the issue.  Can you please let me know what the correct URI construction should be to access the edit profile flow?

Many thanks

**Comment by pamelafox** [comment]
I'm not sure offhand about the correct URI construction- I'd have to actually implement the suggested change and see the result. Looks like @rayluo has assigned this issue to himself, so hopefully he can chime in.

**Comment by jimma72** [comment]
Thanks Pamela.  I'll wait to hear from @rayluo.  Thanks for the response



________________________________

**Comment by jimma72** [comment]
@rayluo have you managed to resolve this issue yet.  I am trying to get the edit profile functionality to work but it still errors as above.  Your help is appreciated.

Thanks
