### ISSUE TITLE
.env was not load

### ISSUE THREAD

**Issue by yc185048** [Azure-Samples/ms-identity-python-webapp#110]
I was going through the example code and found the .env file was not load automatically. I added the following to `app_config.py` file
```python
from dotenv import load_dotenv
load_dotenv()
```

Not sure if it is intended behavior. If not I can create a PR for this. Thanks.

**Comment by rayluo** [comment]
Quoted from [Flask's documentation](https://flask.palletsprojects.com/en/2.3.x/cli/#environment-variables-from-dotenv):

> If [python-dotenv](https://github.com/theskumar/python-dotenv#readme) is installed, running the flask command will set environment variables defined in the files .env

Does that not for you? Which Flask version are you using?

**Comment by yc185048** [comment]
My bad. I start up the app by running `python app.py` instead of using `python -m flask run` command. It would be good to add extra note for this behavior. Just my though. Thank you!

**Comment by rayluo** [comment]
> My bad. I start up the app by running `python app.py` instead of using `python -m flask run` command. It would be good to add extra note for this behavior. Just my though. Thank you!

We can certainly see what we can improve here. But can you provide more info?

I tried `python app.py` and it can still load `.env`. I want to get to the bottom of this issue. Which Flask and python-dotenv versions are you using?

**Comment by yc185048** [comment]
Sure. Here is the version info from my pip list
Flask                     2.2.5
Flask-Session      0.4.1
python-dotenv    0.21.1
Python                 3.10.11

One other thing is I didn't use virtualenv for python env management. I use conda for the python and install package through pip and requirement files.
