### ISSUE TITLE
after successful authentication, how to  redirect users to the same page from which they started

### ISSUE THREAD

**Issue by duduniao** [Azure-Samples/ms-identity-python-webapp#117]
Redirect URIs are fixed, how to implement this function？

**Comment by rayluo** [comment]
This sample does not currently support this behavior out of the box. Marking this as an enhancement request, for now. You can subscribe/watch this repo for its future releases.

Basically, we will need to use a state mechanism to store the url of the page to be redirected into.

**Comment by rayluo** [comment]
This will be achieved as a byproduct of merging in #136
