### ISSUE TITLE
About Entra External ID for customers

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/ms-identity-python-webapp#131]
Hello,

May I know if it's possible to modify this example to use for the new Entran External ID for customers? A bit of details would be quite helpful.

Thanks!

**Comment by rayluo** [comment]
You mean Entra External ID, formerly known as B2C? This sample already supports that. Please follow our ["If you are configuring your B2C app" section in the README](https://github.com/Azure-Samples/ms-identity-python-webapp?tab=readme-ov-file#if-you-are-configuring-your-b2c-app).
