### ISSUE TITLE
Sign in  Replacement tokens customization file (apps.json) absent?

### ISSUE THREAD

**Issue by mwanzias** [Azure-Samples/ms-identity-python-webapp#134]
We have some automated scenarios, there are files we depend on to have the code automatically replace the tokens and configure the authority. The files seem to have been dropped in this specific edition of samples. 

That is the apps.json file in the **AppCreationScripts**  is it possible to be reinstated? there are a few structural differences between sample.json and apps.json the apps.json would be what we use for the automated replacement process for the appId, client secret and any other client specific configuraitons.

The section of interest in the apps.json file had this kind of configurations

 "codeConfigurations": [
                {
                    "settingFile": ".env",
                    "replaceTokens": {
                        "appId": "Enter_the_Application_Id_Here",
                        "tenantName": "Enter_the_Tenant_Subdomain_Here"
                    }
                },
            ]

**Comment by mwanzias** [comment]
In addition to the above the env file is ommitted/ git ignored from the commit and therefore can only allow people to create it using the Configure.ps1 file in the AppCreationScripts as such leaving this only to a usable state of one who has to run the sample app by probably running the app manually. Our automated scenario will require to have this file automatically populated with Id's but not created by the configure script only.

**Comment by SHERMANOUKO** [comment]
@mwanzias lets discuss this internally please.

**Comment by rayluo** [comment]
We discussed offline. We agreed that the samples will not provide a configuration file existing in Version Control System; instead, the automation scripts shall populate a configure file (currently a `.env`) on-the-fly.
