### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: The main branch does not have the html files

### ISSUE THREAD

**Issue by wartrax13** [Azure-Samples/ms-identity-python-webapp#153]

**Comment by C0N50** [comment]
Hey wartrax13,

We were able to fix the template not found error by taking the html files off of the main repo, creating an identity folder under templates and then copying the files in.

https://github.com/Azure-Samples/ms-identity-python/tree/main/ms_identity_python/templates/identity

**Comment by wartrax13** [comment]
Hi @C0N50 !
Obviously.
I left the issue so that newbies who are reading the documentation that directs this repository do not fall into this trap. The repository owner could put the templates... it doesn't cost anything.

**Comment by zynk** [comment]
Thank you for leaving this up, very annoying.
