### ISSUE TITLE
go to the requested url rather than home page

### ISSUE THREAD

**Issue by santhoshbomma9** [Azure-Samples/ms-identity-python-webapp#22]
Hi @rayluo 
Is there a way to implement this? I am unable to store the requested url when the login flow happens and it just keeps going to the home/main page.

**Comment by rayluo** [comment]
Understood. While we may consider to add this into our sample, this is largely a topic of web framework usage. The following approach would probably work (I haven't tested it, though):

You can try to store the requested url into session, BEFORE the login flow. And then, after the successful login, in the home i.e. `/index` page (at line 17.5), you can add a redirect based on the stored url in session.

**Comment by santhoshbomma9** [comment]
Sure, thanks @rayluo, didnt want to use the session but seems like the only option. I will try that.

**Comment by rayluo** [comment]
It is not the only option, but it is probably the easiest/cheapest option, given that you get the session functionality for free, and we are already using it for other things anyway.

**Comment by santhoshbomma9** [comment]
yes true! Thanks @rayluo !
