### ISSUE TITLE
AppCreationScripts\Configure.ps1 error

### ISSUE THREAD

**Issue by YannMSFT** [Azure-Samples/ms-identity-python-webapp#24]
While executing the script from the main folder (as suggested in the README file), it returns an error, trying to get content from ..\app_config.py (the file being in fact in the current folder).

I guess the $configFile variable in "configure.ps1:228" should be set as
$pwd.Path + "\app_config.py"
Rather than
$pwd.Path + "\..\app_config.py"

No problem while executing the script from the AppCreationScripts folder.

**Comment by rayluo** [comment]
@jmprieur @abhidnya13 Can one of you take a look here? Thanks

**Comment by idg-sam** [comment]
Merged https://github.com/Azure-Samples/ms-identity-python-webapp/pull/43
Thanks @YannMSFT
