### ISSUE TITLE
ModuleNotFoundError: No module named 'werkzeug.contrib'

### ISSUE THREAD

**Issue by ianbroad** [Azure-Samples/ms-identity-python-webapp#25]
When I run the sample I get this error:

ModuleNotFoundError: No module named 'werkzeug.contrib'

**Comment by ianbroad** [comment]
Sorry, I didn't realize I needed a lesser version.

**Comment by rayluo** [comment]
@ianbroad Were you hinting your "lesser version" workaround as [the first message here](https://github.com/Azure-Samples/ms-identity-python-webapp/issues/16#issue-564319955)? But we had a better workaround mentioned as [the last message here](https://github.com/Azure-Samples/ms-identity-python-webapp/issues/16#issuecomment-618168231). Does it not work for you?
