### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by dfoley84** [Azure-Samples/ms-identity-python-webapp#33]
What would be causing the following issue? 

SSLError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/v2.0/.well-known/openid-configuration (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by rayluo** [comment]
Is this issue reproducible?

The clue might be in this part of the error message: `SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)`. Among first several search results, I found [this post](https://medium.com/@audun.nes/sslerror-bad-handshake-when-using-azure-cli-6db6a6e63062) might be useful here.

**Comment by dfoley84** [comment]
Configured a Self Signed Cert.

**Comment by rayluo** [comment]
Glad that you found your solution. Out of curiosity, wasn't you trying to access `login.microsoftonline.com`, according to the error message? Why would that Microsoft-owned website require you to configure a self-signed cert?
