### ISSUE TITLE
How to get the email of the authenticated user?

### ISSUE THREAD

**Issue by rjouhann** [Azure-Samples/ms-identity-python-webapp#40]
Hello,
I am looking a way to retrieve the user email of the authenticated user.
I can get the first and last name, as showing in the sample example but I can't figure out a way to get the email.
Thanks for your help!
Best Regards,
Romain

**Comment by rayluo** [comment]
You will need two things:

* Our sample passes the [value of `session["user"]`](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/app.py#L24) into template. Such value is a dict in itself. And [our default template displays its `user["name"]` only](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/templates/index.html#L8). Display its full content to see what you have.

* You will typically find a key-value pair `'preferred_username': 'johndoe@example.com'` but, strictly speaking, that is NOT the ~droid~ email you are looking for! To have a real email in user object, you would need to add `"email"` into [scope configuration](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/master/app_config.py#L26) beforehand.

**Comment by rjouhann** [comment]
thanks!
