### ISSUE TITLE
webapp redirects to login page in GCP App Engine

### ISSUE THREAD

**Issue by chiokejjones** [Azure-Samples/ms-identity-python-webapp#42]
After testing it locally, I've deployed the sample app to GCP App Engine Standard. I'm running into an issue where the application seems to authenticate back to AAD, but it redirects back to the login page.

I haven't made any changes to the most recent code or requirements. My `app.yaml` file only contains the runtime configuration.

Browser console shows the redirect that grabs the token, redirect back to the app:

![image](https://user-images.githubusercontent.com/30128510/89577976-15bfb280-d7f7-11ea-90ee-dbff92519e0b.png)

Has anyone experienced this issue before?

**Comment by rayluo** [comment]
Hmm, I haven't tried deploying this sample app into GCP App Engine. But based on my GAE experience many years before, GAE does not support local file system. Is it still the case? This sample app currently uses a server-side session which would be persisted on server-side file system. If that file system does not work, it might cause such issue. (That being said, if a file system were not available, it should error out much earlier.)

**Comment by chiokejjones** [comment]
Thanks for the information. GAE does allow writing out to Cloud Storage [https://cloud.google.com/appengine/docs/standard/python3/storage-options](url) or using the temporary storage [https://cloud.google.com/appengine/docs/standard/python3/using-temp-files](url).

**Comment by rayluo** [comment]
Nope, neither the [Google Cloud Storage](https://cloud.google.com/appengine/docs/standard/python3/using-cloud-storage) nor its [temporary storage](https://cloud.google.com/appengine/docs/standard/python3/using-temp-files) is a regular local file system. [This Q&A in Stackoverflow explains why](https://stackoverflow.com/a/59082920/728675), and it also suggests you to consider a VM with local storage. That indeed seems to be the only option, for now.

**Comment by chiokejjones** [comment]
Thanks for the explanation. Is the server-side session a requirement of the library?

**Comment by rayluo** [comment]
> Is the server-side session a requirement of the library?

You are commenting in a web app sample which is powered by MSAL (MicroSoft Authentication Library).

Server-side session is NOT a requirement of MSAL, but it is currently the approach this web app sample is built. Your options are:
* either uses this sample i.e. follows its server-side session design decision, and then you choose a VM infrastructure to host your app
* or you can implement a different web app, based on client-side session protected by encryption

**Comment by chiokejjones** [comment]
Thanks for your patience Ray.
