### ISSUE TITLE
How can this sample be modified to be used with managed identity?

### ISSUE THREAD

**Issue by abagherp** [Azure-Samples/ms-identity-python-webapp#60]
I am trying to modify this sample to use system-assigned identity of my application, to sign in the user and query basic information. Is there any example of that? And generally, would it be possible to replicate the behaviour of this sample using managed identity?

**Comment by jmprieur** [comment]
I'd suggest you have a look at the Azure SDK for Python: https://github.com/Azure/azure-sdk-for-python
