### ISSUE TITLE
Ensure User is logged in before redirecting to a Different Page

### ISSUE THREAD

**Issue by nfoley84** [Azure-Samples/ms-identity-python-webapp#61]
Hi, 

looking at the Code for the index; you are getting the session.get if there is no session you are redirecting them to login.
Can I do the same if I want to ensure someone is logged in before they go to a different page if a user goes types in localhost/dashboard on the application? 
can I use session.get()  or do I need to import Flask Login and use @login_required? 

```
@app.route("/dashboard")
def dashboard():
   If not session.get("user"):
     return redirect(url_for("login"))
  
  #Do Something
  return render_template('dashboard.html')
```

**Comment by rayluo** [comment]
Hi @nfoley84 , thanks for registering on github just to ask us this question. We are honoured to have you here. :-)

This sample app was designed on top of [vanilla](https://en.wikipedia.org/wiki/Vanilla_software) Flask (see also ["What Flask is, What Flask is Not"](https://flask.palletsprojects.com/en/1.1.x/design/#what-flask-is-what-flask-is-not)), so, Flask Login is not relevant in this sample.

And yes, currently the [`if not session.get("user"): return redirect(url_for("login"))`](https://github.com/Azure-Samples/ms-identity-python-webapp/blob/0.3.0/app.py#L22-L23) is the right pattern to detect whether the end user has logged in. Presumably, this is the most easy-to-understand way. (Note: In future versions, if/when the underlying sign-in/sign-out logic become more complex, we may introduce our own `@login_required` decorator. You can use the "Watch" button at the upper right of the current github page to subscribe future release notes, to get informed with latest new features.)

**Comment by nfoley84** [comment]
Thanks @rayluo.
