### ISSUE TITLE
RuntimeError: 0. The ID token is not yet valid.

### ISSUE THREAD

**Issue by taoisu** [Azure-Samples/ms-identity-python-webapp#66]
Following the instructions in the README.md, when I login with my org account (xiaguo@microsoft.com), I got error "RuntimeError: 0. The ID token is not yet valid."

I tried to figure out what's going on, somehow the "nbf" returned is way later than now
![image](https://user-images.githubusercontent.com/30015018/121459244-be7ef700-c95f-11eb-9c73-25490edbf16c.png)

What can I do to solve this issue? Thanks for your answer!

**Comment by rayluo** [comment]
I tried it just now, with my org account (also in microsoft.com), and it worked for me. Can you reproduce this issue?

**Comment by taoisu** [comment]
Thanks @rayluo! It looks like the issue is with my system time, I'm using WSL and somehow it's time is not synced to the latest, after I forced time sync, everything is fine now.
