### ISSUE TITLE
The provided client secret keys are expired

### ISSUE THREAD

**Issue by marc181982** [Azure-Samples/ms-identity-python-webapp#67]
I just keep running into the error below once I logged with my user account. I've tried different Azure AD tenants and browsers, but the same error message keeps appearing. Also tried generating a new secret even though I'm sure its not expired.

invalid_client
AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials Trace ID: fff84e51-e60e-4599-bdc6-6d6685207601 Correlation ID: 83ddadd9-4d95-44f4-99e5-36a2401e8faf Timestamp: 2021-06-19 15:14:59Z

**Comment by rayluo** [comment]
I tried my test app just now, and it worked for me. Searching keyword `AADSTS7000222` out there gives similar suggestions as to update your client secret. For example, this one: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2/issues/87
