### ISSUE TITLE
Integration in Flask with  blueprints and application factory pattern for a large application 

### ISSUE THREAD

**Issue by s-AlirezaSadeghi** [Azure-Samples/ms-identity-python-webapp#69]
I've been looking to integrate ms-identity with an existing (flask) project. I've looked around and so far haven't found a structure that allows for integration of (flask) using app factory and Blueprints with ms-identity. 

 I know in Application factory pattern you use current_app ( which is a proxy ) to access the app in blueprints, but doing the same is not possible as ms-identity (ContextAdaptor) requires flask_app instance and not a proxy as shown below.

![image](https://user-images.githubusercontent.com/41008322/132637965-0c07daed-c368-4de6-bbf4-02e7bc4618e8.png)

Is there a best practice/way on structuring Flask app that allows for such integration of MS-identity and Blueprints ?

**Comment by mregni** [comment]
I know this is a very old thread but did you ever found a solution for this? @s-AlirezaSadeghi

**Comment by george-kuanli-peng** [comment]
This repo has blueprint integration

https://github.com/Azure-Samples/ms-identity-python-samples-common

**Comment by benkey0** [comment]
Did anyone get any further with this? 

I am unable to import the decorator and use it in blueprints. Flask Dance seems to work with only B2C and not Internal only which doesnt work for my requirements.

**Comment by pamelafox** [comment]
This sample now uses the identity package, a higher-level package that wraps msal operations. I have modified a sample Blueprint app to use the identity package, and it seems to work well. Here's a blog post with details on how I achieved the integration:
https://blog.pamelafox.org/2023/03/adding-microsoft-graph-authentication.html
Hopefully that helps those of you looking to integrate with your Blueprint apps. Please let me know if you have issues adapting my integration or if you have your own approaches to share.

**Comment by rayluo** [comment]
With the upcoming #136 , I believe there is no need to wrap this sample into blueprint.
