### ISSUE TITLE
Example application works locally but fails on cloud foundry

### ISSUE THREAD

**Issue by JonathanChiang** [Azure-Samples/ms-identity-python-webapp#99]
When I try to login through cloud foundry created url, I get routed to this error. Not sure how to proceed. Any tips or guidance is greatly appreciated

Login Failure
invalid_grant
state missing from auth_code_flow

**Comment by loopasam** [comment]
I faced a similar issue, see this thread: https://github.com/Azure-Samples/ms-identity-python-webapp/issues/94

Not sure whether it's related or not, in my case it was caused by a race condition coming from the favicon. To debug you could try to log every single request coming to the app and inspect for anything unexpected.

**Comment by JonathanChiang** [comment]
Hi, 

I zipped the latest repo and tried it again, altering only the app_config. It works out of box with one instance and I reproduce the error when I run cloud foundry on 3.  

I was looking into session storage prior to reading your response, so I will continue to do so. 

If there is any documentation on multiple instances that you can point me to that would be great. Thanks for your help and thanks @loopasam for additional insight.

**Comment by rayluo** [comment]
> I was looking into session storage prior to reading your response, so I will continue to do so.

Great. Let us know how that goes.

We may also work in this area to see what we can do. If you haven't already, please subscribe (i.e. click the Watch button on this repo's homepage) to receive future updates. (Hmm, why do I sound like a youtuber...)

**Comment by JonathanChiang** [comment]
Awesome, yes and subscribed. If you decide to post tutorials on youtube I will also subscribe :)
